# -*- coding: utf-8 -*-
"""lector de audios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11N59m9cINkjSeul_4cC24QIRhg1by2mD
"""

!pip install -q openai-whisper
!sudo apt -y install ffmpeg
!pip install googletrans==4.0.0-rc1

import whisper
from googletrans import Translator

from google.colab import files

# Subir archivo (mp3, wav, m4a, etc.)
audio_file = files.upload()

# Cargar modelo (puede ser: tiny, base, small, medium, large)
model = whisper.load_model("base")

# Cambia 'tu_audio.mp3' por el nombre real del archivo que subiste
result = model.transcribe("HOMEWORK W2.mp3")

texto = result["text"]
print("Texto original:", texto)

# Traducir
translator = Translator()
traduccion = translator.translate(texto, src="en", dest="es")  # de inglés a español
print("Traducción:", traduccion.text)

Texto original: Hello, how are you today?
Traducción: Hola, ¿cómo estás hoy?

from google.colab import files

files.download('translated_text.txt')

with open("translated_text.txt", "w") as f:
    f.write(traduccion.text)

print("Translated text saved to translated_text.txt")